alias p3='python3'
alias tor='cd ~/Downloads/tor-browser/;./start-tor-browser.desktop --deattach ; cd ; exit'
alias fa='vim ~/.bash_aliases'
alias firefox='gtk-launch org.mozilla.firefox.desktop' 
alias v='vim' 
